import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Nav";
import Head from "next/head";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <Head>
          {/* Correctly preload a font */}
          <link
            rel="preload"
            href="/fonts/my-font.woff2"
            as="font"
            type="font/woff2"
            crossOrigin="anonymous"
          />
        </Head>
      <body
        className={cn(
          "min-h-screen bg-zinc-900 font-sans antialiased",
          fontSans.variable
        )}
      >
        <Navbar />
        {children}{" "}
      </body>
    </html>
  );
}
